---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - zhangyi6324/noctalia-shell
    install:
      packages:
        - niri
        - noctalia-shell

  - type: chezmoi
    repository: "https://github.com/chillpert/dotfiles"
    all-users: true
    file-conflict-policy: replace

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.keepassxc.KeePassXC
          - org.vinegarhq.Sober
          - dev.diegovsky.Riff
          - im.riot.Riot
          - org.telegram.desktop
          - org.signal.Signal
          - com.protonvpn.www
          - com.dec05eba.gpu_screen_recorder
      - scope: user

  - type: os-release
    properties:
      ID: chillpert-os
      NAME: chillpert-os
      PRETTY_NAME: Chillpert OS

  - type: signing
